Update Docusaurus to 2.0 (#485)
* build(docs): update package-lock to v2

The new package-lock version contains more details and is more explicit.
Before updating packages with npm it makes sense to update this.

* deps(docs): bump docusaurus to 2.0.1

* fix(docs): move hideableSidebar config

This fixes the following error at startup:

> [ERROR] ValidationError: themeConfig.hideableSidebar has been moved to
> themeConfig.docs.sidebar.hideable.

* fix(docs): use new algolia appId

This was a new requirement from DocSearch. See
https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration for
more details.

* fix(docs): align new css urls

It seems the urls are resolved differently now. The previous urls caused
compilation errors during `npm start`. Removing the `feel-scala` prefix
fixed these errors.

* ci(docs): update to node v18

* deps(docs): update to fix webpack

See:
- https://github.com/facebook/docusaurus/issues/5778
- https://github.com/TypeStrong/ts-node/pull/1645